/* DIAGNOSTIC RESULTS */
export const FETCH_DIAGNOSTICS = "FETCH_DIAGNOSTICS"
export const FETCH_DIAGNOSTICS_SUCCESS = "FETCH_DIAGNOSTICS_SUCCESS"
export const FETCH_DIAGNOSTICS_FAIL = "FETCH_DIAGNOSTICS_FAIL"
