/* LOGS */
export const SUBMIT_QUERY = "SUBMIT_QUERY"
export const SUBMIT_QUERY_SUCCESS = "SUBMIT_QUERY_SUCCESS"
export const SUBMIT_QUERY_FAIL = "SUBMIT_QUERY_FAIL"
export const GET_EXPERIMENTS = "GET_EXPERIMENTS"
export const GET_EXPERIMENTS_SUCCESS = "GET_EXPERIMENTS_SUCCESS"
export const GET_EXPERIMENTS_FAIL = "GET_EXPERIMENTS_FAIL"
